### ISSUE TITLE
Dump SMT Queries From Test Suite in SMTComp Format

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#122]
We are collaborating with the centaur lab at stanford (developers of cvc5 & bitwuzla), and we need to produce a set of benchmarks that they can use to start optimising cvc5 / bitwuzla for our use case.

We should start by dumping all the queries from our existing test suite in a format as close to the SMTComp format as possible and put them into a separate git repo that we can give to stanford. 

Ideally this procedure should be automated within hevm so we can easily update the bechmark repo as the test suite expands.

**Comment by msooseth** [comment]
I think the SMT2 format we generate is the same as what the SMT Competition uses. However, we may want to be careful of the test cases we provide. We should try to provide queries that span the easy-moderate-hard-impossible spectrum, that are representative of the queries that we think will be used by the "average user" and the "power user". Generating a good set of benchmarks is actually really hard, so we shouldn't spend _too_ much time on it, but perhaps we could think of how to adjust the test suite to add scenarios that may be relevant to such users.

**Comment by d-xo** [comment]
yes definitely agree. would be great to add some real world contracts. Also ones that are too hard. 

I think the deposit contract, the vat from maker, uniswap v2 are all good and should be achievable up to some iteration bound.

major token implementations and utility libraries like solmate are also interesting.

We should also have some more modern stuff, seaport would be a great target for the equivalence checker.

**Comment by msooseth** [comment]
Queries have been dumped to [1] and have been communicated to the CVC team. Closing.

[1] https://github.com/msooseth/eth-bench-smt-queries
