### ISSUE TITLE
Fuzz tests for equivalence checker

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#13]
We can fuzz the equivalence checker (and the solc optimizer) by:

1. generating random yul
2. running the optimizer on it
3. compile both optimized & unoptimized yul to bytecode and run the equivalence checker

**Comment by msooseth** [comment]
This has been resolved (mostly) with the fuzzer that generates random bytecode, compiles it to an Expr, then adds to the Expr a concrete input and  calls `simplify`, then checks the output against the output of `geth`.
