### ISSUE TITLE
`cabal run hevm` out of gas error bug

### ISSUE THREAD

**Issue by DessertHeart** [ethereum/hevm#144]
bash run `cabal run -- hevm -- exec --code 0x647175696e6550 --gas 0xffffffff --state ./mystate --debug`
but got error `Out of gas 0 3`
<img width="970" alt="image" src="https://user-images.githubusercontent.com/93460127/208567786-5d2c3aa6-8ada-40bc-ac99-a6930213ef81.png">
debug showed gas = 0, it seems like command `--gas 0xffffffff` didn't work. plz tell me how to fix it, thanks!

**Comment by d-xo** [comment]
Thanks for the report! This was a silly regression, fixed in #145
