### ISSUE TITLE
Bug: HEVM `store` cheat code is not affecting state variables

### ISSUE THREAD

**Issue by webthethird** [ethereum/hevm#170]
Reposting [this issue from the Echidna fuzzer](https://github.com/crytic/echidna/issues/904) here, since it looks like an upstream issue with HEVM.

See [TestStore.sol](https://github.com/webthethird/solidity-diff-fuzz-upgrades/blob/main/src/test/example/testStore.sol) for a very simple assertion test using Echidna to reproduce this bug.

Using the HEVM cheat code `store` does appear to have some effect on the target contract's storage, because a subsequent call to the `load` cheat code returns the expected value. But when accessing the public state variable directly, i.e., by calling `c.owner()`, the value remains unchanged. The contract for which I am trying to change the state is about as simple as possible, with just a single public state variable and a constructor that sets it to `msg.sender`.

I had the same issue with both the 2.0.4 binary downloaded from the releases page and the one I got from the CI pipeline, built yesterday.

Here is the coverage report generated by Echidna when testing the contract linked above, in which you can see that `load` and `owner()` are returning different values, despite both loading from storage slot 0 (Note: the r's indicate the path of execution which reverted. The fact that the execution got to line 20 indicates that using `load` on slot 0 of contract `c` at line 19 did return the expected value, thus passing the `assert` statement, yet the following line's `assert` failed. So, there is an inconsistency between what HEVM thinks the storage value is and the value of the state variable itself):
```solidity
/home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/compound/testStore.sol
  1 | r   | // SPDX-License-Identifier: MIT
  2 |     | pragma solidity ^0.8.0;
  3 |     | 
  4 |     | import "../example/Smartian_motiv.sol";
  5 |     | import "../helpers.sol";
  6 | r   | 
  7 |     | contract TestStore {
  8 |     |     address admin;
  9 |     |     C c;
 10 |     | 
 11 |     |     constructor() {
 12 |     |         admin = msg.sender;
 13 |     |     }
 14 |     | 
 15 | r   |     function testStore() public {
 16 | r   |         c = new C();
 17 | r   |         require(c.owner() == address(this));
 18 | r   |         CheatCodes(HEVM_ADDRESS).store(address(c), bytes32(0), bytes32(bytes20(admin)));
 19 | r   |         assert(address(bytes20(CheatCodes(HEVM_ADDRESS).load(address(c), bytes32(0)))) == admin);
 20 | r   |         assert(c.owner() == admin);
 21 |     |     }
 22 |     | }

/home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/example/simplest_example.sol
  1 |     | // SPDX-License-Identifier: MIT
  2 |     | pragma solidity ^0.8.0;
  3 | r   | 
  4 |     | contract C {
  5 | r   |   address public owner;
  6 |     | 
  7 |     |   constructor() { // Constructor
  8 |     |     owner = msg.sender;
  9 |     |   }
 10 |     | }

/home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/helpers.sol
  1 |     | // SPDX-License-Identifier: MIT
  2 |     | pragma solidity ^0.8.9;
  3 |     | 
  4 | r   | address constant HEVM_ADDRESS = 0x7109709ECfa91a80626fF3989D68f67F5b1DD12D;
  5 |     | interface CheatCodes {
  6 |     |     // Performs a foreign function call via terminal.
  7 |     |     function ffi(string[] calldata) external returns (bytes memory);
  8 |     |     // Foundry: Generate new fuzzing inputs if conditional not met.
  9 |     |     function assume(bool) external;
 10 |     |     // Sets the block timestamp to x
 11 |     |     function warp(uint x) external;
 12 |     |     // Sets the block number to x
 13 |     |     function roll(uint x) external;
 14 |     |     // Sets the slot loc of contract c to val
 15 |     |     function store(address c, bytes32 loc, bytes32 val) external;
 16 |     |     // Reads the slot loc of contract c
 17 |     |     function load(address c, bytes32 loc) external returns (bytes32 val);
 18 |     |     // Signs the digest using the private key sk. Note that signatures produced via hevm.sign will leak the private key
 19 |     |     function sign(uint sk, bytes32 digest) external returns (uint8 v, bytes32 r, bytes32 s);
 20 |     |     // Derives an ethereum address from the private key sk. 
 21 |     |     // Note that hevm.addr(0) will fail with BadCheatCode as 0 is an invalid ECDSA private key
 22 |     |     function addr(uint sk) external returns (address addr);
 23 |     | }
 ```
And here's a snippet from the Echidna output to the terminal:
```
Analyzing contract: /home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/compound/testStore.sol:TestStore
testStore(): failed!💥  
  Call sequence:
    testStore()

Event sequence: Panic(1)
AssertionFailed(..):  fuzzing (48/999999)
```

**Comment by d-xo** [comment]
Thanks for the report, and sorry for the delayed response. I took a look here and afaict the issue in your test is related to how solidity inserts padding bytes when casting from `address` into `bytes32` via `bytes20`.

Calling `bytes32(bytes20(admin))` produces `0x00a329c0648769a73afac7f9381e08fb43dbea72000000000000000000000000` (i.e. right padded), but addresses should be left padded. 

This means when you store this value in slot 0 on `c`, and then call `c.owner()` we get back `0x381e08FB43DbEa72000000000000000000000000`, i.e. the rightmost 20 bytes of the stored value, which does not match the `admin` address and triggers the assertion violation.

If instead of casting into `bytes32` via `bytes20` I use `bytes32(uint256(uint160(admin)))` then the correct value is returned from the call to `c.owner()` and neither of the assertions is violated.

**Comment by webthethird** [comment]
Thank you!
