### ISSUE TITLE
Produce Aarch64 Binaries for MacOS

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#186]
Since https://github.com/ethereum/hevm/pull/185  we have "static" binaries for x86 macos. We should also produce similar binaries for aarch64. Doing so will require a custom arm macos runner for ci, since these are not yet provided by github.

**Comment by sambacha** [comment]
> Since https://github.com/ethereum/hevm/pull/185  we have "static" binaries for x86 macos. We should also produce similar binaries for aarch64. Doing so will require a custom arm macos runner for ci, since these are not yet provided by github.

What macOS SDK version would you want to target to minimally support? 

We have been building custom binaries using different linker/non universal builds for tooling and can do this potentially

**Comment by d-xo** [comment]
Interesting!

I don't really understand what a macOS SDK version is. I think supporting the latest OS version only would be fine if that's easiest.

**Comment by sambacha** [comment]
> Interesting!
> 
> 
> 
> I don't really understand what a macOS SDK version is. I think supporting the latest OS version only would be fine if that's easiest.

> A macOS SDK is an on-disk directory that contains header files and meta information for macOS APIs. Apple distributes SDKs as part of the Xcode app bundle. Each Xcode version comes with one macOS SDK, the SDK for the most recent released version of macOS at the time of the Xcode release. 


The SDK used for building an app determines three things:

Whether your code compiles at all,
which range of macOS versions your app can run on (available deployment targets), and
certain aspects of runtime behavior.

source: https://firefox-source-docs.mozilla.org/widget/cocoa/sdks.html#overriding-sdk-dependent-runtime-behavior

This table provides more info on  xcode versions and what they support: https://en.m.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)

**Comment by sambacha** [comment]
Related issues: 
https://github.com/crytic/echidna/commit/2711374501fd9d46b3eb97fe169a20c3ee1d3e0a

https://github.com/crytic/echidna/commit/37270701a7b8b896cb758dc75dd3092e35ee4319

**Comment by d-xo** [comment]
I believe the compact unwind stuff is fixed on main: https://github.com/ethereum/hevm/pull/281. Are we still missing anything?

**Comment by elopez** [comment]
GitHub now offers M1 runners that you can use on Actions jobs, with one caveat: the organization must have large runners enabled. I believe this has a monetary cost.

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

Other than that, it should be easy to start producing aarch64 binaries with the same Nix way used for x86_64 now, as I [observed here](https://github.com/ethereum/hevm/pull/415#issuecomment-1779623432).

**Comment by msooseth** [comment]
Yesss this has now been merged. We need to get a new release cut and then these binaries will be released automatically. Closing :)
