### ISSUE TITLE
`WriteWord` simplification can be wrong when offset is large

### ISSUE THREAD

**Issue by msooseth** [ethereum/hevm#207]
The PR pipeline of  https://github.com/ethereum/hevm/pull/198 broke (see logs [here](https://pipelines.actions.githubusercontent.com/serviceHosts/847bf41c-3bf4-44e1-aa43-2f4738618db6/_apis/pipelines/1/runs/1286/signedlogcontent/3?urlExpires=2023-02-24T16%3A06%3A11.4229503Z&urlSigningMethod=HMACV1&urlSignature=u7%2Btuew3yRsTUtM0dt2CXBqNuqDt2l5%2FxaxzFDpdZCc%3D )) because this randomly generation expression, unrated to the PR itself:

`EVM.Expr.simplify WriteWord (SDiv (Sub (LT (Lit 0x1a) (Lit 0x2b)) (Lit 0x59)) (Lit 0x57)) (Lit 0xba0f7483eaf0000033e5f50af97000007b670a8fe8e000017b866ff8ee9) (WriteWord (Lit 0x10) (Lit 0x194f1c1b0a5600000ccdec88b707000004743426102c000005e06b915fdc) (AbstractBuf "esc_NFIIGOFlwfrBCZWnIWOEvFBT"))`

Overflows Expr.simplify, in particular, the offset (SDiv (Sub (LT (Lit 0x1a) (Lit 0x2b)) (Lit 0x59)) (Lit 0x57)) happens to be:

```
EVM.Expr.simplify (SDiv (Sub (LT (Lit 0x1a) (Lit 0x2b)) (Lit 0x59)) (Lit 0x57))
Lit 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

i.e. very large. This is related to the CopySlice simplifier overflow, where a similar issue happened and has been fixed by @zoep .

**Comment by asymmetric** [comment]
@msooseth not sure if you're aware, but [this url](https://pipelines.actions.githubusercontent.com/serviceHosts/847bf41c-3bf4-44e1-aa43-2f4738618db6/_apis/pipelines/1/runs/1286/signedlogcontent/3?urlExpires=2023-02-24T16%3A06%3A11.4229503Z&urlSigningMethod=HMACV1&urlSignature=u7%2Btuew3yRsTUtM0dt2CXBqNuqDt2l5%2FxaxzFDpdZCc%3D) doesn't resolve anymore.

**Comment by msooseth** [comment]
@asymmetric Thanks! I'll attach the GitHub build action link next time. Sorry, and thanks for letting me know :+1:
