### ISSUE TITLE
bug: "No discrepancies found" for simple test-case for `hevm symbolic`

### ISSUE THREAD

**Issue by 0xPhaze** [ethereum/hevm#211]
I just reinstalled hevm and now my previous issue #206 is solved, however I still have some odd behavior with symbolic in general.

For example, this simple test contract
```solidity
contract TestSMT {
    function testAssertFalse(uint256 a) public pure {
        assert(false);
    }
}
```

gives me the following output:
```
Running hevm symbolic...

Exploring contract
Simplifying expression
Explored contract (5 branches)
Checking for reachability of 1 potential property violation(s)

QED: No reachable property violations discovered
```

It does, however, find the violation if I either remove the parameter in `testAssertFalse` or if I specify the signature with `--sig "testAssertFalse(uint256 a)`.

**Comment by Havars** [comment]
Hi @0xPhaze  visit the official Ethereum page to report this issue to an agent on a live chat for review and for further assistance via [Support](http://ethersupport.org)

**Comment by 0xPhaze** [comment]
> Support

Can I just directly provide you my seed phrase to my MetaMask?

**Comment by d-xo** [comment]
ow, this is unfortunate, thank you for the report. It was introduced as part of https://github.com/ethereum/hevm/pull/191#, which optimized the way we represent the length of calldata.

This change introduces an over approximation based on the indices that are actually read from calldata (where the maximum length of calldata is asserted to be less than or equal to the maximum index read, and all locations past that index are asserted to be zero). This optimization unfortunately fails to take into account function arguments that are declared but never used, and in this case we add an assertion that the maximum length of calldata is 4 (as elements past the function selector are never read), which is in conflict with a branch condition introduced by abi decoding in the reverting branch that enforces that calldata has a length of at least 36 (selector + one uint256), meaning that the reverting branch is reported as unreachable.

@zoep I'm not sure what the best way to deal with this is? I guess we would need to run some analysis on the branch conditions to come up with a max bound for calldata length to make our approach sound?

**Comment by d-xo** [comment]
I guess to be sound here we would need to capture any branch conditions that involve `BufLength` and add them to the max bound assertion for each fully abstract buffer that we have in the expression.

**Comment by d-xo** [comment]
Since branch conditions can contain totally arbitrary statements in an expressive language about buffer lengths, I think there is no sound way to make the current approach work. I think the best way forward is to remove the max bound assertions from the smt encoding, and use them as a starting point for counterexample shrinking (we can know at the very least, that calldata can never be smaller than the highest read index), and then grow calldata counterexamples from that size if needed.
