### ISSUE TITLE
Bug: `prank` underflows balance if sending too much ETH in `msg.value`

### ISSUE THREAD

**Issue by rappie** [ethereum/hevm#247]
This should be self-explanatory. I can provide example code if necessary.

Related:
https://github.com/ethereum/hevm/issues/240

Example output from Echidna:
![image](https://user-images.githubusercontent.com/1430820/231860316-6948734d-803c-4899-9b27-5d2e8a58d693.png)

I've done the math :smile: 
`(second number - first number) + third number == 2**256`

**Comment by d-xo** [comment]
reproduced, thanks a lot for the report :)

**Comment by d-xo** [comment]
Should be fixed by #251
