### ISSUE TITLE
hevm does not support deal cheatcode

### ISSUE THREAD

**Issue by acmLL** [ethereum/hevm#257]
When I try to run hevm with commands like

vm.deal(address(weth), 100e18);

it reports a vague error message like this one

Running 1 tests for test/scWETH.t_c.sol:scWETHUnitTest
[BAIL] setUp() 

"Failure: setUp\n  \n\n"%

**Comment by msooseth** [comment]
This should be close by #354

**Comment by msooseth** [comment]
Please let us know if this issue still persists! Thanks again for creating the issue :)
