### ISSUE TITLE
CI Failing on Windows

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#260]
CI started failing on windows, I think because of: https://github.com/haskell/network/pull/549. I'm not sure how best to fix this. 

Logs here: https://github.com/ethereum/hevm/actions/runs/4991168529/jobs/8937297629

@elopez do you have any ideas on how to proceed?

**Comment by elopez** [comment]
Not sure what might be going on, maybe we should bring this issue upstream 👍  My first suspicion would be that it is missing the `afunix_compat.h` header in install-includes, as the failure appears to be during building `network-bsd` and not `network` itself? https://github.com/haskell/network/blob/2f0ef784d358571e678be147ba05b48296270f09/network.cabal#L125-L126

**Comment by d-xo** [comment]
There is some discussion about why this is failing on GHC <= 9.2 in this pr: https://github.com/haskell/network/pull/549#issuecomment-1523930822. I'm not really sure if / how we can fix this downstream. Filing and upstream issue seems sensible. I'm disabling ci on windows here for now until we have a fix.
