### ISSUE TITLE
Static Binaries for MacOS

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#27]
Running `nix-build` on macos currently fails with:

```
> ld: library not found for -lm
> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
> `cc' failed in phase `Linker'. (Exit code: 1)
```

This seems to related to: `https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/Libm/default.nix`.

We should fix this and start producing static binaries for macos (ideally both aarch64 and x86_64).

**Comment by msooseth** [comment]
@zoep has this been fixed? If so, can we close it?

**Comment by d-xo** [comment]
nix-build works on macos, but the resulting binaries are not yet static
