### ISSUE TITLE
Memory leak with writeWord

### ISSUE THREAD

**Issue by siraben** [ethereum/hevm#292]
## Description

I am experiencing a substantial memory usage problem when running the following EVM bytecode `6127105b6001900360206000208062989680600051065260005280600090116100035760206000f3`. This handwritten program loops `N = 10000` times, repeatedly hashes a number `x:=0`, writes it into address `sha3(x) mod M` (where `M = 10000000`), and then sets `x=sha3(x)`. When running with the flags `+RTS -s -RTS`, it reports allocating 249 gigabytes in the heap over the life of the process.

Please ensure that hevm outputs the expected hash: `0x067b44cb1cc46275b78df229d6f92be8f1fa5e549748b6a6ca60abc43577a8cd`

## Screenshot
The following screenshot shows the memory used as a function of `N` and `M`. Note the axes are log scale, and the units are log of bytes for the allocation.
<p align="center">
<img width="416" alt="3D plot of allocations" src="https://github.com/ethereum/hevm/assets/8219659/514f9ab6-5a7e-43a4-b662-584c899d33a0">
</p>

## To Reproduce

1. `cabal run hevm -- +RTS -s -RTS exec --code 6127105b6001900360206000208062989680600051065260005280600090116100035760206000f3`
2. Observe stderr.

## Expected behavior

The program should run without such a high memory footprint.

## Actual behavior

When the bytecode is run, the RTS stats show:

- 249,738,106,088 bytes allocated in the heap
- 110,774,448 bytes copied during GC
- 92,058,902,352 bytes maximum residency (17 sample(s))
- 4,398,416,048 bytes maximum slop
- 100036 MiB total memory in use (17 MB lost due to fragmentation)

The total time taken is 9.606s with 29.905s elapsed. 

The allocations appear to scale up with the number of loop iterations, with the `writeWord` function consuming the majority of allocations and calls.

### Additional context

You can find the assembler used for the program here: https://github.com/siraben/evm-assembler

```lisp
10000 ;; loop counter (n)

(label loop)
1 - ;; decrement counter
32 0 sha3 dup ;; h := sha3(mem[0..31])
10000000 ;; m
0 @ mod ! ;; mem[mem[0] mod m] := h
0 ! ;; mem[0] := h

dup 0 > (jumpi loop) ;; jump if counter != 0

32 0 return
```

In the program, `n` is the loop counter and `m` is the modulo factor. This means that any memory up to address `m` could potentially be addressed, resulting in higher memory usage as `m` increases.

The issue may reside in the `writeWord` function, and its handling of the strict `ByteString` in `ConcreteBuf`. Here's the suspected function for reference:

```haskell
writeWord o@(Lit offset) v@(Lit val) buf@(ConcreteBuf src)
  | offset + 32 < maxBytes
    = ConcreteBuf $ (padRight (num offset) $ BS.take (num offset) src)
                 <> word256Bytes val
                 <> BS.drop ((num offset) + 32) src
  | otherwise = WriteWord o v buf
```

### Discussion Link

The issue was first discussed on [Matrix](https://matrix.to/#/!xwFjsWobKyQMEThogz:matrix.org/$KyzTDoB8gfhxoEAAWNYlvQu6EJbHBiaziOp6CAAzYnE?via=matrix.org&via=matrix.dapp.org.uk&via=matrix.ocamlot.xyz).

**Comment by d-xo** [comment]
Thanks for such a clear write up! Do you have any insights or ideas for potential fixes?

**Comment by siraben** [comment]
I think the behavior I was expecting was that at any point in the program with a concrete memory, the size of `buf` should be at most the largest addressed memory. I'd need to read up again on how Solidity manages memory to see if this is feasible (IIRC they use hashing + offset for maps). Maybe we could have some sparse representation of memory passed around linearly, since a memory location is always 0 unless a non-zero value was written to it last.

**Comment by d-xo** [comment]
> I think the behavior I was expecting was that at any point in the program with a concrete memory, the size of `buf` should be at most the largest addressed memory address. 

totally agree

> I'd need to read up again on how Solidity manages memory to see if this is feasible (IIRC they use hashing + offset for maps).

This is more relevant for storage than memory. 

> Maybe we could have some sparse representation of memory passed around linearly, since a memory location is always 0 unless a non-zero value was written to it last.

Interesting idea. I guess the primary issue here though is that we're keeping around references to old versions of memory somewhere? I had a little dig into the implementation of `writeWord` and didn't see any obvious leaks. I guess the next step is to dig in to some heap profiling tools to track down where our retained references are?

**Comment by d-xo** [comment]
@msooseth and I spent some time today debugging and think that we nailed down the source of the leak in this program. It seems like it's due to the change here: https://github.com/ethereum/hevm/commit/7b1adbd6149c57f67eedbdc17032722701f75057#diff-26e87ea7d3dec16c517b6c327812b1217a164d463b93239a3c3d47eb29b70ae0L656-R659. If I skip the call to `branch` for a concrete jump condition then I see the following memory usage on the reproducer:

```
< cabal run hevm -- +RTS -s -RTS exec --code 6127105b6001900360206000208062989680600051065260005280600090116100035760206000f3
Up to date
Starting ghc-debug on socket: /tmp/ghc-debug
"Return: 0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563"
         762,672 bytes allocated in the heap
         187,856 bytes copied during GC
         249,144 bytes maximum residency (1 sample(s))
         185,032 bytes maximum slop
             100 MiB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         0 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         1 colls,     0 par    0.000s   0.000s     0.0002s    0.0002s

  TASKS: 43 (1 bound, 42 peak workers (42 total), using -N20)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.006s  (  0.013s elapsed)
  MUT     time    0.001s  (  0.001s elapsed)
  GC      time    0.000s  (  0.000s elapsed)
  EXIT    time    0.003s  (  0.006s elapsed)
  Total   time    0.010s  (  0.020s elapsed)

  Alloc rate    776,839,216 bytes per MUT second

  Productivity   9.7% of total user, 3.5% of total elapsed
  ```
  
 I need to think more about how to best fix this properlly, should have a pr soon. @siraben thanks so much for the awesome detective work here.

**Comment by d-xo** [comment]
I'm still not really sure I fully understand the root cause of the leak here, but I'm guessing we have some deeper issues related to lazy evaluation of `Stepper`s? I think the issue is probably that `Stepper` evaluation first produces a sequence of bound monadic actions (each of which contains a fully copy of the VM state inside it's continuation) before finally collapsing this down to some concrete value? The change in `https://github.com/ethereum/hevm/commit/7b1adbd6149c57f67eedbdc17032722701f75057` really exposes this flaw beccause every concrete `JUMPI` now results in a  new monadic action in this long chain of thunks. I'm guessing that switching all our interpreters to the more direct style in `Exec.hs` would be the deeper fix to this issue. I need to do some more testing to validate this theory.

@arcz if I understood correctly echidna does not make use of the `Stepper` pattern? Are you able to reproduce this leak inside of echidna?

**Comment by siraben** [comment]
@d-xo this is how go-ethereum handles memory, https://github.com/ethereum/go-ethereum/blob/c2db667c8f824ec0d025cbde95e6aaad67fc10ba/core/vm/memory.go#L24

**Comment by siraben** [comment]
Further follow up with heap profiling. Shows that the ARR_WORDS (internal name for `ByteArray#`) is making up most of the memory used.

`cabal run hevm --ghc-options='-O2 -rtsopts -finfo-table-map -fdistinct-constructor-tables' -- +RTS -l -hT -i0.5 -RTS exec --code 6127105b6001900360206000208062989680600051065260005280600090116100035760206000f3`
<img width="811" alt="Screenshot 2023-07-10 at 19 41 26" src="https://github.com/ethereum/hevm/assets/8219659/93fff6d4-3e03-47b8-a039-8fac241833b0">

No provenance information though.
`cabal run hevm --ghc-options='-O2 -rtsopts -finfo-table-map -fdistinct-constructor-tables' -- +RTS -l -hi -i0.5 -RTS exec --code 6127105b6001900360206000208062989680600051065260005280600090116100035760206000f3`
<img width="1261" alt="Screenshot 2023-07-10 at 19 40 18" src="https://github.com/ethereum/hevm/assets/8219659/febb083c-0645-4ded-a963-8bd00e49715d">

**Comment by siraben** [comment]
Here is a version that uses storage operations instead, `6127105b60019003600054600052602060002080629896806000540655600055806000901161000357602060005460005260206000f3`

No leak here.
```
"Return: 0x067b44cb1cc46275b78df229d6f92be8f1fa5e549748b6a6ca60abc43577a8cd"
     555,096,096 bytes allocated in the heap
      36,513,672 bytes copied during GC
      23,639,976 bytes maximum residency (7 sample(s))
         542,808 bytes maximum slop
              86 MiB total memory in use (0 MB lost due to fragmentation)
```

**Comment by d-xo** [comment]
I went back and looked at the change that I made to the branching code and there was a mistake :woman_facepalming:, this meant that my change "fixed" the leak by simply never branching. Thanks a lot @arcz and @siraben for digging deeper here. 

After a bit of discussion via chat with @arcz we decided that moving forward with the `St` based mutable memory is probably the best solution here.
