### ISSUE TITLE
Let's move to newer Z3

### ISSUE THREAD

**Issue by msooseth** [ethereum/hevm#297]
Attached file [a.smt2.gz](https://github.com/ethereum/hevm/files/11980871/a.smt2.gz) solves with our version of Z3 in 3s, but solves with newer Z3 in 0.1 seconds.

```
[nix-shell:~/development/hevm]$ /usr/bin/time --verbose z3 a.smt2 
unsat
        Command being timed: "z3 a.smt2"
        User time (seconds): 3.89
        System time (seconds): 0.75
[nix-shell:~/development/hevm]$ z3 --version
Z3 version 4.8.15 - 64 bit
```

Newer Z3:

```
$/usr/bin/time --verbose z3 a.smt2
unsat
        Command being timed: "z3 a.smt2"
        User time (seconds): 0.01
        System time (seconds): 0.00
$ z3 --version
Z3 version 4.12.1 - 64 bit
```

Funnily enough, CVC5 in our nix is slower than either of the Z3's on this example:

```
[nix-shell:~/development/hevm]$ /usr/bin/time --verbose cvc5 a.smt2 
unsat
        Command being timed: "cvc5 a.smt2"
        User time (seconds): 32.80
[nix-shell:~/development/hevm]$ cvc5 --version
This is cvc5 version 1.0.4
compiled with GCC version 12.2.0
```

Latest CVC5:

```
$ /usr/bin/time --verbose ./bin/cvc5 ../../hevm/a.smt2
unsat
        Command being timed: "./bin/cvc5 ../../hevm/a.smt2"
        User time (seconds): 31.72
        System time (seconds): 1.68
        Percent of CPU this job got: 99%
$ ./bin/cvc5 --version
This is cvc5 version 1.0.6-dev.199.718395f17 [git 718395f17 on branch main]
compiled with GCC version 13.1.1 20230429
on Jul  7 2023 12:40:41
```

So latest CVC5 is not any better, either.

**Comment by msooseth** [comment]
Note that bitwuzla (latest GIT version) does not parse the SMT2 file:

```
$ ./src/main/bitwuzla ../../hevm/a.smt2 
[error] ../../hevm/a.smt2:43:2: expected command at 'define-const'
```

**Comment by d-xo** [comment]
I think this should be fixed by: https://github.com/ethereum/hevm/pull/248, and if not that then https://github.com/ethereum/hevm/pull/303 should for sure...

**Comment by arcz** [comment]
The default z3 version is pinned to 4.8.X in nixpkgs, but there are the newer versions available under different attributes: https://github.com/NixOS/nixpkgs/blob/547a750222e2dc5a07a3d085dc5a165b7b44cdd8/pkgs/applications/science/logic/z3/default.nix#L91-L107
