### ISSUE TITLE
Reversed Keccaks Need Constraints

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#385]
We introduced a simplification stage where we will reverse concrete keccak outputs into calls into keccak on concrete inputs. This lets us pattern match on them and opens up ways that we can simplify storage reads / writes. 

These terms appear in the final expression that gets sent to the solver, and we don't currently include constraints about their value. We should either simplify them down to a concrete value again before sending them to the solver, or we should add the required constraints. This results in us producing incorrect models in some cases.

**Comment by msooseth** [comment]
Yeah, this was definitely an issue. I fixed this by #406  -- there, the final value sent to the solver is always the concrete value. Hence, this becomes a non-issue.

**Comment by msooseth** [comment]
Closed as part of #406
