### ISSUE TITLE
Different behaviors for expected to revert function

### ISSUE THREAD

**Issue by acmLL** [ethereum/hevm#418]
Configuration:
MacBook Pro, Apple M1 Pro, Sonoma 14.0, 32GB

hevm version: 0.52.0 (static version)

+++++++++++++++ Scenario +++++++++++++++++++
Given this function

    function setSlippageTolerance(uint256 newSlippageTolerance) external onlyAdmin {
        if (newSlippageTolerance > C.ONE) revert InvalidSlippageTolerance();
        slippageTolerance = newSlippageTolerance;
        emit SlippageToleranceUpdated(msg.sender, newSlippageTolerance);
    }

where *** uint256 public constant ONE = 1e18; ***

and this test function

    function test_reverts_setSlippageTolerance(uint256 newslippageTolerance) public {
        if(newslippageTolerance > C.ONE) {
            try vault.setSlippageTolerance(newslippageTolerance) {
                assert(false);
            }
            catch {
                assert(true);
            }
        }
    }

The above test function reports PASS in forge test and hevm test (using prove instead of test). The above code is the only one that seems to work properly with hevm test. But when we change the test function to

    function test_reverts_setSlippageTolerance(uint256 newslippageTolerance) public {
        if(newslippageTolerance > C.ONE) {
            vm.expectRevert();
            vault.setSlippageTolerance(C.ONE);
        }
    }

Only forge test reports FAIL because the above function will not revert indeed. hevm test reports PASS (using the prefix prove). And by changing the prefix to proveFail, hevm test reports FAIL with "result:   Successful execution". What is the expected behavior here? Or is it a bug indeed?

**Comment by acmLL** [comment]
Forget about this. This is related to another issue that I opened up and already closed... Thanks

**Comment by msooseth** [comment]
Oh, do you mean issue #419 ? Can I close this issue then? :smiley:

**Comment by acmLL** [comment]
Hi, I just provided an example @d_xo asked. Thanks!

**Comment by msooseth** [comment]
OK, thanks! So we'll track this at #419 I'm closing this and picking that up :) Thanks again for reporting!
