### ISSUE TITLE
Cancun upgrade

### ISSUE THREAD

**Issue by arcz** [ethereum/hevm#469]
We need to implement Cancun fork:
https://github.com/aalimsahin/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dencun.md

- [x] [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
- [x] [EIP-4788: Beacon block root in the EVM](https://eips.ethereum.org/EIPS/eip-4788)
- [ ] [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)
- [x] [EIP-5656: MCOPY - Memory copying instruction](https://eips.ethereum.org/EIPS/eip-5656)
- [x] [EIP-6780: SELFDESTRUCT only in same transaction](https://eips.ethereum.org/EIPS/eip-6780)
- [x] [EIP-7514: Add Max Epoch Churn Limit](https://eips.ethereum.org/EIPS/eip-7514)
- [x] [EIP-7516: BLOBBASEFEE opcode](https://eips.ethereum.org/EIPS/eip-7516)

**Comment by msooseth** [comment]
Hi,

Thanks for packing it all together and creating an issue! Maybe not too hard to implement :)

At the same time, hevm is still far from being even _used_ in the symbolic execution sense :cry:  There was a bug where the released binary didn't even work for most people for the past ~6 months, and _nobody_ caught it. That's... bad. So I am a bit conflicted on what to spend time on. If a tree falls in a forest and no one is around to hear it, does it make a sound? I'm not so sure. I'd rather lots of people heard the tree falling, maybe they'd complain, or fix it, or something. So I wanna make this thing more approachable, more usable, easier to access.

What do you think?

**Comment by 0xalpharush** [comment]
I believe these won't require changes since they pertain to the consensus layer:
[EIP-7044: Perpetually Valid Signed Voluntary Exits](https://eips.ethereum.org/EIPS/eip-7044)
 [EIP-7045: Increase Max Attestation Inclusion Slot](https://eips.ethereum.org/EIPS/eip-7045)

**Comment by msooseth** [comment]
Right, I'll pick some things up here and elsewhere in the issues. I am finally back from my research break so I hopefully can start things moving :)

**Comment by ethever** [comment]
Hi, any progress about this issue?

**Comment by msooseth** [comment]
MCOPY/TSTORE/TLOAD is in #529  Then I think we only need a few small things to get this to go through!

**Comment by msooseth** [comment]
I think we won't need to bother with:
- [x] [EIP-4788: Beacon block root in the EVM](https://eips.ethereum.org/EIPS/eip-4788)
- [x] [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)
- [x] [EIP-7514: Add Max Epoch Churn Limit](https://eips.ethereum.org/EIPS/eip-7514)

These need implementation:
- [ ]  [EIP-5656: MCOPY - Memory copying instruction](https://eips.ethereum.org/EIPS/eip-5656)
- [ ] [EIP-6780: SELFDESTRUCT only in same transaction](https://eips.ethereum.org/EIPS/eip-6780)
- [ ] [EIP-7516: BLOBBASEFEE opcode](https://eips.ethereum.org/EIPS/eip-7516)

**Comment by msooseth** [comment]
@ethever do you wanna try out the newest `main`? I think it should work for most cases now.

**Comment by eilgug** [comment]
@msooseth so is the newest `main` supporting the MCOPY function now? Is it also supporting new cheat codes by any chance? (for example `vm.label(address, name)`)

**Comment by arcz** [comment]
@eilgug yes, both things are now implemented in main

**Comment by msooseth** [comment]
Yes, mostly thanks to @arcz :heart_eyes:

**Comment by msooseth** [comment]
Yay, closing!
