### ISSUE TITLE
Display hexadecimal value of panic opcode or specific error msgs for a panic 

### ISSUE THREAD

**Issue by 0xicingdeath** [ethereum/hevm#473]
### Describe the desired feature

Consider displaying the hexadecimal value of the panic opcode or the [specific error messages](https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require) that are represented by the `Panic(17)`. Since this number is technically in decimal, it needs to be converted into hex for `Panic(0x11)`, thereby allowing us to determine that it is due to an arithmetic operation causing underflow. 

```
 └╴error Revert Panic(17) <no source map>
```
see [Echidna issue](https://github.com/crytic/echidna/issues/1210) counterpart

**Comment by msooseth** [comment]
Please see & review: https://github.com/ethereum/hevm/pull/474

Thanks!
