### ISSUE TITLE
Investigate possible nondeterminism in our test suite

### ISSUE THREAD

**Issue by blishko** [ethereum/hevm#553]
I have observed some nondeterministic behaviour with some of our tests, both on my laptop and in CI
From time to time, one test fails (but I don't know if it is the same one every time or not), or some tests take much longer than usual.

**Comment by msooseth** [comment]
This is due to the fuzz tests I think? It uses a different seed each time
for e.g. the simplifier tests that auto generate Expr-s randomly. So that’s
100% expected. Other variations are not really. Although SMT solvers could
be nondeterministic, but I hope they aren’t…

**Comment by blishko** [comment]
I am pretty sure I have seen nondeterministic behaviour in other tests.

**Comment by msooseth** [comment]
Ooops :S Can you maybe try to track them down? Would be good to know…

**Comment by blishko** [comment]
That's why I created the issue :)
I am just not sure when I will get to that.

**Comment by msooseth** [comment]
I think what happened is that the abi-encoder fuzzer can sometimes generate a pretty complicated calldata that takes forever to encode. I definitely observed this and it was pretty frustrating. I have opened #544.

I have also labelled this as enhancement, because it doesn't actually affect any user, it's "only" an enhancement for us :)

**Comment by msooseth** [comment]
So the new additions to #555 could be the trick. There was not only nondeterminsim but a potential bug when running multi-threaded thanks to some monadic magic + `concurrently`.

**Comment by blishko** [comment]
I think you were right that the behaviour I was observing were the property-based tests that generate different expressions every time.
