### ISSUE TITLE
How can i run hevm in vscode?

### ISSUE THREAD

**Issue by ethever** [ethereum/hevm#594]
I cloned hevm github repo into local machine.
And then I `nix-shell` in the directory.
I try to run `cabal build`  and it success.

And then I `code .` to open this directory in vscode.
And then the `Haskell` vscode extension(haskell.haskell) work for me. 
Here is its log:
``` txt
...
...
...
2024-10-12T05:39:58.100934Z | Info | Starting server
2024-10-12T05:39:58.102609Z | Info | Registering IDE configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-6520124636527659025) "file:///root/projects/hevm_forked/hevm"], clientSettings = hashed Nothing}
2024-10-12T05:39:58.105388Z | Info | Started LSP server in 0.00s
2024-10-12T05:39:59.060356Z | Info | Cradle path: src/EVM/SymExec.hs
2024-10-12T05:39:59.061109Z | Info | invoking build tool to determine build flags (this may take some time depending on the cache)
2024-10-12T05:39:59.999785Z | Info | Load cabal cradle using single file
2024-10-12T05:40:00.659390Z | Info | cabal --builddir=/root/.cache/hie-bios/dist-hevm-dbaf228d34b3f3309ffd5cc82cf459d2 v2-repl --with-compiler /root/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf lib:hevm
  Environment Variables
    HIE_BIOS_OUTPUT: /run/user/0/HIE_BIOS_OUTPUT163985-0
    HIE_BIOS_GHC: /root/.ghcup/ghc/9.4.8/lib/ghc-9.4.8/bin/ghc-9.4.8
    HIE_BIOS_GHC_ARGS: -B/root/.ghcup/ghc/9.4.8/lib/ghc-9.4.8/lib
2024-10-12T05:40:06.186114Z | Warning | semanticTokens: SemanticTokens' dependency error: Rule Failed: GetHieAst
[Error - 1:40:06 PM] Request textDocument/codeLens failed.
  Message: moduleName: Rule Failed: GhcSession
  Code: -32803 
[Error - 1:40:06 PM] Request textDocument/foldingRange failed.
  Message: codeRange: Rule Failed: GetCodeRange
  Code: -32803 
[Error - 1:40:06 PM] Request textDocument/semanticTokens/full failed.
  Message: semanticTokens: Rule Failed: GetSemanticTokens
  Code: -32803 
[Error - 1:40:13 PM] Request textDocument/codeLens failed.
  Message: moduleName: Rule Failed: GhcSession
  Code: -32803 
2024-10-12T05:40:58.131632Z | Info | Live bytes: 0.00MB Heap size: 0.00MB
2024-10-12T05:41:58.192125Z | Info | Live bytes: 0.00MB Heap size: 0.00MB
2024-10-12T05:42:58.236494Z | Info | Live bytes: 0.00MB Heap size: 0.00MB
[Error - 1:43:30 PM] Request textDocument/foldingRange failed.
  Message: codeRange: Rule Failed: GetCodeRange
  Code: -32803 
[Error - 1:43:30 PM] Request textDocument/semanticTokens/full failed.
  Message: semanticTokens: Rule Failed: GetSemanticTokens
  Code: -32803 
[Error - 1:43:36 PM] Request textDocument/codeLens failed.
  Message: moduleName: Rule Failed: GhcSession
  Code: -32803 
[Error - 1:43:36 PM] Request textDocument/foldingRange failed.
  Message: codeRange: Rule Failed: GetCodeRange
  Code: -32803 
```
As you can see some error got, so i run 
``` bash
 cabal --builddir=/root/.cache/hie-bios/dist-hevm-dbaf228d34b3f3309ffd5cc82cf459d2 v2-repl --with-compiler /root/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf lib:hevm
``` in the nix-shell. But i got:
``` bash
[nix-shell:~/projects/hevm_forked/hevm]# cabal --builddir=/root/.cache/hie-bios/dist-hevm-dbaf228d34b3f3309ffd5cc82cf459d2 v2-repl --with-compiler /root/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf lib:hevm
Error: [Cabal-4000]
Version mismatch between ghc and ghc-pkg: /root/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 is version 9.6.6 /root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf is version 9.4.8
```
It seems all error I meet comes from the version divergence of ghc and ghc-pkg. I have no idea who generated the two scripts  `/root/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36`&`/root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf` automatically. 
Here is what they contain:
``` bash
[nix-shell:~/projects/hevm_forked/hevm]# cat /root/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36
#!/usr/bin/env bash

function out(){
  echo "$1" >> "$HIE_BIOS_OUTPUT"
}

if [ "$1" == "--interactive" ]; then
  out "$(pwd)"
  for arg in "$@"; do
    out "$arg"
  done
else
  "${HIE_BIOS_GHC:-ghc}" "${HIE_BIOS_GHC_ARGS}" "$@"
fi
```
``` bash
[nix-shell:~/projects/hevm_forked/hevm]# cat  /root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf
#!/bin/sh
exec /root/.ghcup/ghc/9.4.8/lib/ghc-9.4.8/bin/ghc-pkg-9.4.8 --global-package-db /root/.ghcup/ghc/9.4.8/lib/ghc-9.4.8/lib/package.conf.d ${1+"$@"}
```

**Comment by ethever** [comment]
ghc's version and ghc-pkg' version are the same in the nix-shell env:
``` bash
[nix-shell:~/projects/hevm_forked/hevm]# ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.6.6

[nix-shell:~/projects/hevm_forked/hevm]# ghc-pkg --version
GHC package manager version 9.6.6
```

**Comment by ethever** [comment]
Sadly, I can never build hevm in vscode(without lsp supportting). For those you developing at hevm, what editor you used? why haskell has such a diverse range of build tools? Could you give me a hand?

**Comment by ethever** [comment]
Tried `nix shell`, `nix-shell`, `nix develop`. Nothing works.

**Comment by msooseth** [comment]
Hi,

I'm sorry you hare having trouble with VSCode. I am using neovim. The haskell language server is included in the `nix-shell`, so it works pretty out-of-the-box, though neovim can be a bit complicated to configure. I suggest using lazyvim: https://github.com/LazyVim/LazyVim There's a pretty good tutorial youtube video, and documentation there, to set it up. If you follow that guide, and launch vim from the console where you are already inside `nix-shell`, it should work like a charm. I personally still build&run from the console, though, maybe just force of habit.

If you haven't used a modal editor, then Neovim can be a bit much. I believe there is a version of all of this with Emacs, too.

VSCode should work as well, no idea why it doesn't. Maybe someone else, like @elopez knows more, he uses VSCode?

**Comment by blishko** [comment]
Hi,

I use VSCode for browsing the code base and making change, but I still run `hevm` from command line.
I run
```
nix develop
code .
```
And it works quite OK for me.

**Comment by elopez** [comment]
> I cloned hevm github repo into local machine. And then I `nix-shell` in the directory. I try to run `cabal build` and it success.
> 
> And then I `code .` to open this directory in vscode. And then the `Haskell` vscode extension(haskell.haskell) work for me. Here is its log:
> 
> ...
> ```shell
> [nix-shell:~/projects/hevm_forked/hevm]# cat  /root/.cache/hie-bios/ghc-pkg-0d01fb14de4f57fc480e0fe9f824febf
> #!/bin/sh
> exec /root/.ghcup/ghc/9.4.8/lib/ghc-9.4.8/bin/ghc-pkg-9.4.8 --global-package-db /root/.ghcup/ghc/9.4.8/lib/ghc-9.4.8/lib/package.conf.d ${1+"$@"}
> ```

It seems you may have mismatched bits and pieces of GHC coming from both Nix and your host OS installation (through ghcup). You may want to remove ghcup and/or any other ghc installations from the host, or at least from $PATH, and then try again. Consider not running vscode or your nix shell as root as well 😅  And clearing up the `.cache` dir if errors persist.

**Comment by elopez** [comment]
@ethever hi, echoing @blishko, `nix develop` plus `code .` gets me a working vscode with working Haskell LSP, and I can run `cabal build` on the vscode terminal and build hevm successfully. What error in particular are you seeing? Make sure there's no previously running vscode instances before you run `code .`, as vscode will reuse any running instance and your environment won't be correctly picked up in that case.

**Comment by ethever** [comment]
> It seems you may have mismatched bits and pieces of GHC coming from both Nix and your host OS installation (through ghcup). You may want to remove ghcup and/or any other ghc installations from the host, or at least from $PATH, and then try again. Consider not running vscode or your nix shell as root as well 😅 And clearing up the `.cache` dir if errors persist.

Thank you so much for your help! It was indeed a conflict between the different installation sources of GHC that was causing the issue.

**Comment by ethever** [comment]
I really appreciate all your assistance.
