### ISSUE TITLE
hevm `startPrank` overrides msg.sender at all call depth levels, making it inconsistent vs foundry and causing unintended operations

### ISSUE THREAD

**Issue by GalloDaSballo** [ethereum/hevm#608]
## Impact

I have written this repo which shows a full repro

https://github.com/Recon-Fuzz/prank-echidna-vs-foundry

Fundamentally, when using `startPrank` and calling a contract that performs a `transferFrom`, echidna (using hevm under the hood), will perform the `transferFrom` with the pranked address instead of the router, causing the transfer to fail

## Mitigation

I believe that the prank should only be enforced at the current call level, a nested call should not longer have it's msg.sender altered

**Comment by msooseth** [comment]
Right, so `overrideCaller` is set from `Nothing` to the address when `startPrank` is called. This also sets `resetCaller` to `False`. Then, when `stopPrank` is called, `overrideCaller` is set to `Nothing`, and `resetCaler` is set to `True`.

So what you are saying would I think mean that when we do another `call`, `overrideCaller` should be reset to `Nothing`, along with `resetCaller` being reset to `True`. Let me make a PR like that, and maybe you can then check if that fixes it. Would that be OK?

**Comment by msooseth** [comment]
So I have a new branch, `fix_prank` that may fix this. I'm trying to check if it does now :)

**Comment by elopez** [comment]
@GalloDaSballo I opened a draft PR on Echidna that uses @msooseth's hevm branch, if you can try it out and see if it behaves as expected now, that'd be great: https://github.com/crytic/echidna/pull/1331

**Comment by msooseth** [comment]
OK, seems to be fixed with `311b4115aed46e3f2db87acaa69fd73b5503bc14`. The corresponding echidna is:

https://github.com/msooseth/echidna/pull/1

You can cone that, go into `fix_prank` branch, then `nix shell`, then `git clone https://github.com/Recon-Fuzz/prank-echidna-vs-foundry` then `cd prank-echidna-vs-foundry` and then `echidna . --contract CryticTester --config echidna.yaml` and it should all pass.

**Comment by GalloDaSballo** [comment]
Have tested this release candidate by @elopez :
https://github.com/crytic/echidna/actions/runs/12081766889

I ran it for 1 Million tests with no reverts
<img width="1129" alt="Screenshot 2024-11-29 at 18 05 39" src="https://github.com/user-attachments/assets/53f94b17-4d7c-47ae-b8eb-2e896aa5d412">


In contrast see the previous version failing in less than 50k tests
<img width="1000" alt="Screenshot 2024-11-29 at 17 59 54" src="https://github.com/user-attachments/assets/690868a9-acc9-4edb-8356-1e943b2e29ee">

**Comment by msooseth** [comment]
Closing as it's now passing and merged. Thanks a lot! :)
