### ISSUE TITLE
Error: unable to parse: .../out/build-info/537f1e3b991a424923519417f7ebc3f1.json

### ISSUE THREAD

**Issue by chief-mobius** [ethereum/hevm#610]
# **Bug Report: Unable to Parse Build-Info File with Hevm**

## **Environment**
- **OS**: macOS (M3), Docker (Ubuntu 20.04), Debian 12  
- **Versions**:  
  - `forge`: `0.2.0 (398ef4a 2024-11-23T00:27:34.394254000Z)`  
  - `hevm`: `0.53.0` (from [GitHub Releases](https://github.com/ethereum/hevm/releases))  

---

## **Steps to Reproduce**
1. Install using [HEVM Docs](https://hevm.dev/install.html):  
   ```bash
   curl -L https://foundry.paradigm.xyz | bash
   foundryup
   forge init demo
   cd demo
   forge build --ast
   hevm test

## **Observed Behavior**
Error during `hevm test`
```
Error: unable to parse: .../out/build-info/537f1e3b991a424923519417f7ebc3f1.json
```

## **Request**
Could you confirm if the issue is related to `forge`'s `build-info` format compatibility with `hevm` or any required workaround? If additional information or debugging steps are needed, please let me know.
Maybe it have some related with [hevm#491](https://github.com/ethereum/hevm/issues/491)?

**Comment by elopez** [comment]
Can you reproduce this on a more recent hevm build? You can get hevm builds from `main` from the CI artifacts if you would like to test with those: https://github.com/ethereum/hevm/actions/workflows/build.yml?query=branch%3Amain
