### ISSUE TITLE
Advanced Fuzzing Pipelines

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#69]
Just noting some ideas that @msooseth and I discussed for nice fuzzing pipelines that we could write if had an Expr -> EVM compiler. 

Compiling an Expr End into EVM bytecode should be fairly simple, especially if we produce yul instead of bytecode directly. Each ITE can be an if-then-else block, and translating return / revert leaves into return / revert statements in yul shouldn't be too hard.

## Concrete Evaulation vs Geth

1. Generate a random Expr End
2. Compile that into evm
3. Execute both against some concrete input value and compare the result

This would test our smt encoding to make sure that it matches the concrete semantics (we could use the concrete semantics from hevm or from geth).

## Symbolic Exec vs Equivalence Checker

1. Generate random bytecode
2. Symbolically exec to produce an Expr
3. Compile the Expr into EVM
4. Run the equivalence checker against both

This would test the symbolic execution engine (and Expr -> EVM compiler) against the equivalence checker.

**Comment by d-xo** [comment]
Actually for the first case we don't even need an Expr -> EVM compiler, we can just generate random bytecode, produce an Expr from it, and then compare both against some concrete value.

**Comment by msooseth** [comment]
Notes to self:

Fuzz input generators:
https://github.com/MariusVanDerWijden/tx-fuzz
https://github.com/MariusVanDerWijden/FuzzyVM

Runners:
https://github.com/holiman/goevmlab

Local branch:
myfuzz

Notes:
* Maybe we could do something with the assembler by @d-xo

**Comment by msooseth** [comment]
This has been implemented in `Tracing.hs`, closing.
